name: Build Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  py3mod:
    name: py3mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          # Install essential build tools
          sudo apt update
          sudo apt install build-essential
          
          # Install autoconf and automake for generating the configure script
          sudo apt install autoconf automake
          
          # Install pkg-config to find necessary libraries and headers
          sudo apt install pkg-config
          
          # Install Python development headers (if using Python bindings)
          sudo apt install python3-dev
          
          # Install additional libraries as needed (e.g., GTK, OpenSSL, zlib)
          sudo apt install libgtk-3-dev libssl-dev zlib1g-dev
          
          # Regenerate the configure script and generate config.h
          autoreconf -i
          ./configure

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4.4.0
        with:
          python-version-file: py/.python-version
          cache: 'poetry'

      - name: Install dependencies
        run:  |
          cd py
          poetry install --no-root

      - name: Build Python extension
        run: |
          cd py
          poetry run python setup.py clean --all
          poetry run python setup.py build_ext --inplace
          ls -la

      - name: Build the package
        run: |
          cd py
          poetry build
          ls -la 

      - name: Upload the dist directory as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: gnubg-build
          path: py/dist/

      - name: Install the built package and run tests
        run: |
          pip install py/build/gnubg-1.01-cp310-cp310-linux_x86_64.whl
          python -c "import gnubg; print(gnubg.__version__)"

      - name: Upload to PyPI (optional)
        if: github.event_name == 'push'
        run: |
          twine upload dist/*